# Multi-level cache with memory and file storage
_target_: shade_io.stores.composite.CompositeStore
write_through: true

stores:
  # L1 Cache: Memory (fast, limited size)
  - _target_: shade_io.stores.memory.MemoryFeatureStore
    max_size_mb: 50
  
  # L2 Cache: Local files (slower, larger)
  - _target_: shade_io.stores.file.FileFeatureStore
    cache_dir: ${paths.cache_dir}/shade_io
    format: npz
    compression: null