# File-based feature storage
_target_: shade_io.stores.file.FileFeatureStore
cache_dir: ${paths.cache_dir}

# Supported formats:
# - pt: PyTorch native format (torch.save/load) - no compression support
# - npz: NumPy format - compression: true/false (uses zlib internally)
# - pkl: Python pickle format - no compression support  
# - arrow: Apache Arrow/Parquet format (requires pyarrow) - compression: snappy, gzip, brotli, lz4, zstd, or null
format: arrow

# Compression behavior by format:
# - pt/pkl: Compression setting is ignored
# - npz: Any non-null value enables zlib compression (numpy default)
# - arrow: Supports Parquet compression types: snappy (default), gzip, brotli, lz4, zstd, null
# Note: For arrow format, null means use Parquet's default (snappy)
compression: null
