# Cheeger feature set configuration
_target_: shade_io.feature_sets.base.SimpleFeatureSet
name: cheeger_features
description: "Cheeger bound-based feature extraction"

# Cheeger feature extractor
extractors:
  _target_: shade.detectors.feature_extractors.cheeger.CheegerFeatureExtractor
  include_violations: true
  compute_self_normalization: true  # Enable R_tilde_ratio, R_uniform_ratio for zero-shot detector
  aggregation: concat