# Filtered feature set with decorator pattern
_target_: shade_io.feature_sets.decorators.FilteredFeatureSet
name: filtered_features

# Base feature set to filter
base:
  _target_: shade_io.feature_sets.base.SimpleFeatureSet
  name: base_features
  extractors: ???

# Filters to apply
filters:
  - _target_: shade_io.feature_sets.filters.RemoveConstantFeaturesFilter
    threshold: 1e-10