# Simple feature set configuration
_target_: shade_io.feature_sets.base.SimpleFeatureSet
name: simple_features
description: "Basic feature extraction"

# Feature extractors (to be provided by user)
extractors: ???